Ai_Fit-main/mylogin/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from users.views import login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view),
    path('auth/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ai_Fit-main/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("facelogin", views.face_login_view, name="face_login"),
    path("logout", views.logout_view, name="logout"),
    path("forgotpw", views.forgotpw_view, name="forgotpw"),
    path("signup", views.signup_view, name="signup"),
    path("useredit", views.user_edit, name='useredit'),
    path("sports/<str:what_kind>", views.sports_view, name="sports"),
    path("sports/counts/<int:count_result>/<str:what_kind>", views.count_view, name="counts")
]

Ai_Fit-main/users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, password, nick_name, date_of_birth, profile_img=None, representation=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            nick_name=nick_name,
            date_of_birth=date_of_birth,
            profile_img=profile_img,
            representation=representation,
        )
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password, nick_name, date_of_birth, profile_img=None, representation=None):
        user = self.create_user(
            email=email,
            password=password,
            nick_name=nick_name,
            date_of_birth=date_of_birth,
            profile_img=profile_img,
            representation=representation,
        )
        user.is_admin = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    nick_name = models.CharField(max_length=20, null=False)
    date_of_birth = models.DateField()

    profile_img = models.ImageField(null=True)
    representation = models.CharField(max_length=10000, null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nick_name', 'date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin
        

class DailyRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    what_kind = models.CharField(max_length=50)
    workout_date = models.DateField('workout date')
    workout_count = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user', 'what_kind', 'workout_date')

Ai_Fit-main/users/forms.py
from django import forms
from datetime import datetime


class LoginForm(forms.Form):
    email = forms.CharField(label='Your Email', max_length=255)
    password = forms.CharField(label='Your Password', max_length=30, widget=forms.PasswordInput)


class SignupForm(forms.Form):
    email = forms.CharField(label='* Email', max_length=255, widget=forms.EmailInput)
    password1 = forms.CharField(label='* Password', min_length=6, max_length=30, widget=forms.PasswordInput)
    password2 = forms.CharField(label='* Password 확인', min_length=6, max_length=30, widget=forms.PasswordInput)
    nick_name = forms.CharField(label="* 닉네임", max_length=10)
    date_of_birth = forms.DateField(label="* 생년월일", initial="2000-01-01", widget=forms.SelectDateWidget(years=range(1900, datetime.today().year + 1)))


class EditForm(forms.Form):
    current_password = forms.CharField(label='* 현재 Password', max_length=30, widget=forms.PasswordInput)
    password1 = forms.CharField(label='* Password', min_length=6, max_length=30, widget=forms.PasswordInput)
    password2 = forms.CharField(label='* Password 확인', min_length=6, max_length=30, widget=forms.PasswordInput)


class ChangePwForm(forms.Form):
    password1 = forms.CharField(label='Password', min_length=6, max_length=30, widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password 확인', min_length=6, max_length=30, widget=forms.PasswordInput)

Ai_Fit-main/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from .forms import LoginForm, SignupForm, EditForm, ChangePwForm
from .models import User, DailyRecord

import base64
from django.core.files.base import ContentFile
# 장고에서 제공해주는 비밀번호 검증 메소드
from django.contrib.auth.hashers import check_password

from datetime import datetime

from . import auth_code

# model 관련 import
import tensorflow as tf
import numpy as np
from numpy import load
from numpy import asarray
from mtcnn.mtcnn import MTCNN
import time
import csv
import re
from os import listdir
import os

from . import image_embedding # 얼굴을 128 벡터로
from . import detect_face_from_one_image # 사진에서 얼굴 추출
from . import anis_koubaa_lib
from . import face_recognition
# 여기까지

# Create your views here.
# 사용자가 F5를 눌러 새로고침을 해줄 수도 있을 텐데 계속 csrf때문에 페이지가 깨지고 뒤로 가더라도 그래프가 보이지 않아 다시 로그인을 해야하는 이슈가 있었다.
# 보안적인 측면에선 좋지 않겠지만 원활한 서비스를 위해 일단 csrf검증을 취소시켜서 해결하였다.
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                latest_records = DailyRecord.objects.filter(user=user.id).order_by('-workout_date')[:30]
                return render(request, "users/login.html", {'latest_records': latest_records})

    elif request.user.is_authenticated:
        user = request.user
        latest_records = DailyRecord.objects.filter(user=user.id).order_by('-workout_date')[:30]
        return render(request, "users/login.html", {'latest_records': latest_records})

    else:
        form = LoginForm()

    return render(request, "users/login.html", {'form': form})


@csrf_exempt
def face_login_view(request):
    if request.method == 'POST':
        m = User.objects.exclude(representation = None).values()
        n = len(User.objects.exclude(representation = None).values())
        face_embeddings = []
        labels = []
        temp = None
        temp2 = []
        # img 얼굴 확인 디텍터
        detector = MTCNN()
        # face모델 불러이기 시간소요됨(4s)
        model = tf.keras.models.load_model('static/model/face/facenet_keras.h5')
        for i in m:
            # string형태로 저장된 값 [] 및 공백 제거
            temp = ','.join(i['representation'].split())[2:-1]
            # print(temp)
            # 쉽표 기준으로 나누어서 리스트화
            if temp[-1] == ',':
                temp2 = temp[:-1].split(',')
            else:
                temp2 = temp.split(',')
            # string이기에 float형태로 변경
            temp2 = list(map(float, temp2))
            # temp2 = np.reshape(temp2,(1,128))

            face_embeddings.append(temp2)
            # print(temp2)
            # print(face_embeddings)
            labels.append(i['id'])
            # print(labels)
            classifier = face_recognition.classification(face_embeddings, labels, n)
        # representation 등록되어있는 회원 분류기 학습 (매번 로그인시마다 진행, 짧음 경과시간)
        # pk = User.objects.get(email= user.email).pk

        data = str(request.body)
        if data != '':
            img_fmt, img_str = data.split(';base64,')
            ext = img_fmt.split('/')[-1]

            profile_img = ContentFile(base64.b64decode(img_str[:-1]), name='profile.' + ext)
            e_img = detect_face_from_one_image.extract_face(detector, profile_img)
            face_to_predict_embedding = image_embedding.get_embedding(model, e_img)
            o_labels, class_probability = face_recognition.predict_label(face_to_predict_embedding, face_embeddings, labels, classifier)

            print(class_probability)

            if (class_probability >= 55):
                t_email = User.objects.get(id=o_labels).email
                user = User.objects.get(email=t_email)
                if user is not None:
                    login(request, user)
                    return HttpResponse("OK_Face")

                form = LoginForm()
                return render(request, "users/login.html", {'form': form})
  
        return HttpResponse(request.body)
    return render(request, "users/facelogin.html")


def logout_view(request):
    logout(request)
    return redirect("users:login")


@csrf_exempt
def forgotpw_view(request):
    context = {'auth': 0}

    if request.method == 'POST':
        contents = request.body.decode('utf-8').split('&')

        if contents[0] == 'request_code':
            try:
                user = User.objects.get(email=contents[1])
            except User.DoesNotExist:
                return HttpResponse("Fail_User")
            else:
                request.session['code'] = auth_code.make_code()
                if not auth_code.send_code('floodfilllinkedlist@gmail.com', 'zssbjrhlobebrvrq', contents[1], request.session['code']):
                    return HttpResponse("Fail_Email")
                request.session['email'] = contents[1]
                request.session['auth'] = 0
                return HttpResponse("OK_Email")

        elif contents[0] == 'request_auth':
            if request.session['code'] == contents[1]:
                request.session['auth'] = 1
                return HttpResponse("OK_Code")
            else:
                return HttpResponse("Fail_Code")

        else:
            form = ChangePwForm(request.POST)
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            if password1 == password2:
                user = User.objects.get(email=request.session['email'])
                user.set_password(password1)
                user.save()

                user = authenticate(email=request.session['email'], password=password1)
                login(request, user)

                del request.session['auth']
                del request.session['email']
                del request.session['code']

                return redirect("users:login")

            else:
                context['form'] = form
                context['error'] = "Password와 Password확인란이 일치하지 않습니다."
                context['email'] = request.session['email']
                context['code'] = request.session['code']
                context['auth'] = request.session['auth']

                return render(request, "users/forgotpw.html", context)
    else:
        context['form'] = ChangePwForm()

    return render(request, "users/forgotpw.html", context)


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)

        if form.is_valid():
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            nick_name = form.cleaned_data['nick_name']
            date_of_birth = form.cleaned_data['date_of_birth']

            data = request.POST['profile_img']
            
            if data != '':
                img_fmt, img_str = data.split(';base64,')
                ext = img_fmt.split('/')[-1]
                profile_img = ContentFile(base64.b64decode(img_str), name='profile.' + ext)
                # face모델 불러이기 시간소요됨(4s)
                model = tf.keras.models.load_model('static/model/face/facenet_keras.h5')
                detector = MTCNN()
                e_img = detect_face_from_one_image.extract_face(detector, profile_img)
                representation = ' '.join(map(str,list(image_embedding.get_embedding(model, e_img))))

            if password1 == password2:
                if data != '':
                    user = User.objects.create_user(email, password1, nick_name, date_of_birth, profile_img, representation)
                    
                else:
                    user = User.objects.create_user(email, password1, nick_name, date_of_birth)
                return redirect("users:login")

    else:
        form = SignupForm()

    return render(request, "users/signup.html", {'form': form})

def user_edit(request):
    context= {}
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            current_password = form.cleaned_data['current_password']
            user = request.user
            data = request.POST['profile_img']

            if data != '':
                img_fmt, img_str = data.split(';base64,')
                ext = img_fmt.split('/')[-1]
                profile_img = ContentFile(base64.b64decode(img_str), name='profile.' + ext)
                # face모델 불러이기 시간소요됨(4s)
                model = tf.keras.models.load_model('static/model/face/facenet_keras.h5')
                detector = MTCNN()
                e_img = detect_face_from_one_image.extract_face(detector, profile_img)
                representation = ' '.join(map(str,list(image_embedding.get_embedding(model, e_img))))
                
            if check_password(current_password,user.password):
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 == password2:
                    user.set_password(password2)

                    if data != '':
                        user.profile_img = profile_img
                        user.representation = representation

                    user.save()
                    login(request,user)
                    return redirect("users:login")
                else:
                    context['form'] = form
                    context.update({'error':"새로운 비밀번호를 다시 확인해주세요."})
                    # context['error'] = '새로운 비밀번호를 다시 확인해주세요.'
            else:
                context['form'] = form
                context.update({'error':"현재 비밀번호가 일치하지 않습니다."})

        return render(request, "users/useredit.html", context )
    else:

Ai_Fit-main/users/templates/users/facelogin.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face Login</title>
    {% load static %}
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/user.css">
    <link rel="stylesheet" href="/static/css/signup.css">
</head>

<body>

<main class="user_body">
<div class="top_line"></div>
<div class="interlock" id="signup_body">
<section class="above">

    <h1>정면으로 웹캠을 응시해주세요</h1> 

    <div class="camera_frame">
        <div id="camera"></div>
        <div id="results"></div>
    </div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.26/webcam.js"></script>
<script>
    Webcam.set({
        image_format: 'jpeg',
        jpeg_quality: 90
    });
    Webcam.attach("#camera");

    let ready = false;
    let myTimer = setInterval(() => {
        if (ready) {
            ready = false;
            sendFaceImage();
        }
    }, 300);

    Webcam.on('live', () => {
        ready = true;
    });

    function sendFaceImage() {
        Webcam.snap(function (data) {
            fetch('/auth/facelogin', {
                method: 'POST',
                body: data,
            })
            .then(e => {
                e.text().then(e => {
                    if (e == 'OK_Face') {
                        clearInterval(myTimer);
                        location.href = "{% url 'users:login' %}";
                        return;
                    }
                    document.getElementById('results').innerHTML = '<img src="' + e + '"/>';
                    ready = true;
                    return e;
                })
                .catch(e => {
                    clearInterval(myTimer);
                    location.href = "{% url 'users:login' %}";
                });
            })
            .catch(e => console.error(e));
        });
    }
</script>

<div class="btn-area" id="btn-area">
    <div>
        <a href="javascript:idpwLogin();">로그인 페이지로 돌아가기</a>
    </div>
    <div>
        <a href="javascript:signup();">회원가입 하러가기</a>
    </div>
</div>

<script>
    function idpwLogin() {
        clearInterval(myTimer);
        location.href = "{% url 'users:login' %}";
    }

    function signup() {
        clearInterval(myTimer);
        location.href = "{% url 'users:signup' %}";
    }
</script>

Ai_Fit-main/users/templates/users/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login & Mypage</title>

    {% load static %}
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/button.css">
    <link rel="stylesheet" href="/static/css/user.css">
    <link rel="stylesheet" href="/static/css/login.css">
    <link rel="stylesheet" href="/static/css/toparea.css">
    <link rel="stylesheet" href="/static/css/mypage.css">

    <script src="/static/js/jquery-3.5.1.min.js"></script>
</head>


<body>

{% if user.is_authenticated %}

<header class="top">
    <div class="profile_box">
        {% if user.profile_img %} 
        <img class="profile_image" src="{{ user.profile_img.url }}" alt="프로필사진">
        {% endif %}
    </div>
    <div class="welcome">
        <div class="user">{{ user.nick_name }}_</div>
    </div>
    <div class="rightside"> 
        <div class="setting_box">
            <div class="infoedit_btn">
                <a href="{% url 'users:useredit' %}">InfoEdit</a>
            </div>
        </div>
        <a href="{% url 'users:logout' %}">Logout</a>
    </div>
</header>

<main> 

<div class="top_line"></div>
<div class="interlock"><!-- 가로세로 연동 -->

<!-- 동영상, 영상 선택 단 -->
<section class="above">
    <!-- SelectBox Button -->
    <div class="selectbox">
        <label for="workouts">select workout_</label>
        <select id="workouts">
            <option value="squat">SQUAT_</option>
            <option value="dumbell_curl">DUMBELLCURL_</option>
        </select>
    </div>

    <!-- 동영상 -->
    <div class="video_wrap">
        <div class="video_frame">
            <video src="{% static 'video/squat.mp4' %}" autoplay loop id="squatVideo"></video>
            <video src="{% static 'video/dumbell_curl.mp4' %}" autoplay loop id="dumbellCurlVideo" style="display: none;"></video>
        </div>
        <div class="text_frame" id="squatText">
            <p>SQUAT</p>
        </div>
        <div class="text_frame" id="dumbellCurlText" style="display: none;">
            <p>DUMBELL CURL</p>
        </div>
    </div>

    <!-- Prev Start Next Button -->
    <div class="btns_frame">
        <div id="prev">
            <div class="btn" id="btn_lr">
                <div class="btn__content" id="btn_lr__content">< prev</div>
                <span id="btn_lr__glitch"></span>
            </div>
        </div>
        <div id="start">
            <div class="btn" id="btn_start">
                <div class="btn__content" id="btn_start__content">Start_</div>
                <span class="btn__label" id="btn_start__label">A.I.FIT</span>
                <span class="btn__glitch"></span>
            </div>
        </div>
        <div id="next">
            <div class="btn" id="btn_lr">
                <div class="btn__content" id="btn_lr__content">next ></div>
                <span id="btn_lr__glitch"></span>
            </div>
        </div>
    </div>
</section>

<hr>

<!-- 기간, 그래프단 -->
<section class="below">

    <!-- Radio Button -->
    <div class="radio_btns">
        운동 기간 선택: 
        <input type="radio" id="week" name="term" value="week" checked="checked">
        <label for="week">1주일</label>
        <input type="radio" id="halfMonth" name="term" value="halfMonth">
        <label for="halfMonth">15일</label>
        <input type="radio" id="month" name="term" value="month">
        <label for="month">30일</label>
    </div>

    <!-- 그래프 처리 -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <div class="graph_frame">
        <canvas id="myChart" width="7" height="4"></canvas>
    </div>
</section>
</div>  

</main>

{% else %}

<main class="user_body">
    <section class="user_form">
        <h1>A.I.FIT</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="int-area">
                {{ form.email }}
                <label for="id_email">EMAIL</label>
            </div>
            <br>
            <div class="int-area">
                {{ form.password }}
                <label for="id_password">PASSWORD</label>
            </div>
            <div class="btn-area">
                <button id="btn_login_form" type="submit" value="로그인">LOGIN</button>
            </div>
        </form>
        <div class="process">
            <a href="{% url 'users:forgotpw' %}">Forgot Password?</a>
            <a href="{% url 'users:face_login' %}">Face Login</a>
            <a href="{% url 'users:signup' %}">회원가입</a>
        </div>
    </section>
</main>

{% endif %}

</body>

<!-- login page script -->
<script> 
    let id = $('#id_email');
    let pw = $('#id_password');
    let btn = $('#btn_login_form');

    $(btn).on('click', function() {
        if($(id).val() == "") {
            $(id).next('label').addClass('warning');
            setTimeout(function() {
                $('label').removeClass('warning');
            }, 1500)
        }
        else if($(pw).val() == "") {
            $(pw).next('label').addClass('warning');
            setTimeout(function() {
                $('label').removeClass('warning');
            }, 1500)
        }
    })
</script>

<!-- 동영상, 영상 선택 단 -->
<script>
    document.addEventListener("DOMContentLoaded", function () {
        let squatVideo = document.querySelector("#squatVideo");
        let dumbellCurlVideo = document.querySelector("#dumbellCurlVideo");
        let squatText = document.querySelector("#squatText");
        let dumbellCurlText = document.querySelector("#dumbellCurlText");
        let prevBtn = document.querySelector("#prev");
        let nextBtn = document.querySelector("#next");
        let startBtn = document.querySelector("#start");
        let selectBox = document.querySelector("#workouts");

        function changeVideo(prev) {
            selectBox.selectedIndex = prev ? selectBox.selectedIndex - 1 : selectBox.selectedIndex + 1;

            if (selectBox.selectedIndex === -1) {
                selectBox.selectedIndex = prev ? selectBox.options.length - 1 : 0;
            }

            selectBox.dispatchEvent(new Event("change"));
        }

        prevBtn.addEventListener("click", function (e) {
            changeVideo(true);
        });

        nextBtn.addEventListener("click", function (e) {
            changeVideo(false);
        });
        
        selectBox.addEventListener("change", function (e) {
            switch (e.target.value) {
                case "squat":
                    squatVideo.style.display = "";
                    dumbellCurlVideo.style.display = "none";
                    squatText.style.display = "";
                    dumbellCurlText.style.display = "none";
                    break;
                case "dumbell_curl":
                    squatVideo.style.display = "none";
                    dumbellCurlVideo.style.display = "";
                    squatText.style.display = "none";
                    dumbellCurlText.style.display = "";
                    break;
            }
            target_kind = e.target.value;
            resetChart();
        });

        startBtn.addEventListener("click", function (e) {
            let what_kind = selectBox.options[selectBox.selectedIndex].value;
            location.href = "/auth/sports/" + what_kind;
        });
    })
</script>

<!-- 기간, 그래프단 -->
<script>
    //DB로 부터 받아온 값을 준비시키기
    let workout_date_temp = [];
    let workout_count_temp = [];
    let what_kinds = [];
    {% for record in latest_records %}
        workout_date_temp.push("{{record.workout_date}}");
        workout_count_temp.push("{{record.workout_count}}");
        what_kinds.push("{{record.what_kind}}");
    {% endfor %}

    //설정값
    let howMuch = 7;
    let target_kind = "squat";

    //function은 스크립트 코드 중에 가장 첫번째로 정의되는 특징이 있어 바로 위에 선언한 myChart를 인지하지 못한다.
    //그래서 화살표 함수를 변수에 담는 방식으로 변경했다. 이렇게 하면 myChart변수가 할당된 이후 함수가 정의되기에 문제가 해결된다.
    let myChart = null;
    let resetChart = () => {
        //본격적으로 그리기 전에 우선 해당 종목의 해당 일수만큼만 보여주기 위한 전처리 작업을 해준다.
        let workout_date = [];
        let workout_count = [];

        let today = new Date();
        let year = today.getFullYear();
        let month = today.getMonth() + 1; //+1을 해줘야 현재 몇월인지가 구해진다.
        let date = today.getDate();

        for (let i = 0, j = 0; i < howMuch; i++) {
            //해당 종목이 아니라면 건너 뛴다. 다만 끝에 다다랐다면 j가 length인 상태로 로직을 진행한다.
            //그러면 아래서 자연히 day는 -1판정을 받으며 진행중인 날짜에 count가 0인 데이터를 채우게 될 것이다.
            if (j < workout_date_temp.length && what_kinds[j] != target_kind) {
                if (++j < workout_date_temp.length) {
                    i--;
                    continue;
                }
            }

            let day = -1;
            if (j < workout_date_temp.length) {
                //일에 대한 숫자를 day로 뽑아낸다.
                day = workout_date_temp[j].split(' ')[2].slice(0, -1);
            }

            if (date == day) {
                workout_date.push(workout_date_temp[j]);
                workout_count.push(workout_count_temp[j]);
                j++;
            } else {
                workout_date.push(year + "년 " + month + "월 " + date + "일");
                workout_count.push(0);
            }

            if (date == 1) {
                if (--month == 0) {
                    year--;
                    month = 12;
                }
                date = new Date(year, month, 0).getDate();
            } else {
                date--;
            }
        }

        //가장 최근 날짜의 데이터가 끝에 가도록 뒤집어준다.
        workout_date.reverse();
        workout_count.reverse();
        
        //본격적으로 그리기 위해 캔버스를 불러온다.
        let ctx = document.getElementById('myChart').getContext('2d');

        //기존의 것을 파괴시켜주지 않으면 마우스로 그래프 영역 위를 움직일 때 기존 그래프의 정보표시창이 반응하여 자꾸 그림이 바뀌게 되는 현상이 발생한다.
        //그래서 myChart가 기존에 그려진 적이 있다면 해당 인스턴스를 파괴하도록 하였다.
        if (myChart != null) {
            myChart.destroy();
        }
        myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: workout_date,
                datasets: [{
                    label: '운동 횟수',
                    data: workout_count,
                    backgroundColor: '#fcee09',
                    borderColor: 'rgba(255, 255, 255, 0.5)',
                    borderWidth: 2
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "rgba(255, 255, 255, 1)",
                        fontSize: 18
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                            stepSize : 2,
                            fontColor : "rgba(255, 255, 255, 0.7)",
                            fontSize : 15,
                        },
                        gridLines:{
                            color: 'rgba(255, 255, 255, 0.3)',
                            lineWidth:2
                        }
                    }],
                    xAxes: [{
                        ticks:{
                            fontColor : 'rgba(255, 255, 255, 0.7)',
                            fontSize : 12
                        },
                        gridLines:{
                            color: "rgba(255, 255, 255, 0.3)",
                            lineWidth: 1
                        }
                    }]
                }
            }
        });
    }

    //input태그의 term이라고 이름붙여진 라디오 태그들 모두에게 본인이 클릭되었을 때에 대한 이벤트 리스너를 달아주었다.
    document.querySelectorAll("input[name='term']").forEach(function (item) {
        item.addEventListener("click", function (e) {
            target_kind = document.querySelector("#workouts").value;
            switch (e.target.id) {
                case "week":
                    howMuch = 7;
                    break;
                case "halfMonth":
                    howMuch = 15;
                    break;
                case "month":
                    howMuch = 30;
                    break;
            }
            resetChart();
        })
    });
    //처음 이 페이지가 로드될 때 아직 이벤트가 발생하지 않았더라도 Chart를 한번 그려준다.
    resetChart();
</script>